d = {}
name = input("Enter your name: ")
lang = input("Enter your favourite language: ")
d.update({name:lang})
name = input("Enter your name: ")
lang = input("Enter your favourite language: ")
d.update({name:lang})
name = input("Enter your name: ")
lang = input("Enter your favourite language: ")
d.update({name:lang})
name = input("Enter your name: ")
lang = input("Enter your favourite language: ")
d.update({name:lang})
name = input("Enter your name: ")
lang = input("Enter your favourite language: ")
d.update({name:lang})
name = input("Enter your name: ")
lang = input("Enter your favourite language: ")
d.update({name:lang})
print(d)